In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv("creditcard.csv")

In [3]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
df.describe()

Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean    94813.859575  1.168375e-15  3.416908e-16 -1.379537e-15  2.074095e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   9.604066e-16  1.487313e-15 -5.556467e-16  1.213481e-16 -2.406331e-15   
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00   
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01   
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01   
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02   
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01   
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01   

       ...           V21           V22           V23           V24  \
count  ...  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   ...  1.654067e-16 -3.568593e-16  2.578648e-16  4.473266e-15   
std    ...  7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01   
min    ... -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00   
25%    ... -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01   
50%    ... -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02   
75%    ...  1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01   
max    ...  2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00   

                V25           V26           V27           V28         Amount  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000   
mean   5.340915e-16  1.683437e-15 -3.660091e-16 -1.227390e-16      88.349619   
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109   
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000   
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000   
50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000   
75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000   
max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000   

               Class  
count  284807.000000  
mean        0.001727  
std         0.041527  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 31 columns]

In [5]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [6]:
df.columns[df.isna().any()]

Index([], dtype='object')

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
train_set, test_set = train_test_split(df, test_size = 0.2, random_state = 42)
print(f"rows in train set = {len(train_set)} \nrows in test set = {len(test_set)}\n")

rows in train set = 227845 
rows in test set = 56962



In [9]:
 from sklearn.model_selection import StratifiedShuffleSplit 
 sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
 for train_index, test_index in sss.split(df, df["Class"]):
     strat_train_set = df.loc[train_index] 
 strat_test_set = df.loc[test_index]


In [10]:
strat_test_set['Class'].value_counts()


0    56864
1       98
Name: Class, dtype: int64

In [11]:
strat_train_set['Class'].value_counts()


0    227451
1       394
Name: Class, dtype: int64

In [12]:
corr_matrix = df.corr()

corr_matrix['Class'].sort_values(ascending = False)





Class     1.000000
V11       0.154876
V4        0.133447
V2        0.091289
V21       0.040413
V19       0.034783
V20       0.020090
V8        0.019875
V27       0.017580
V28       0.009536
Amount    0.005632
V26       0.004455
V25       0.003308
V22       0.000805
V23      -0.002685
V15      -0.004223
V13      -0.004570
V24      -0.007221
Time     -0.012323
V6       -0.043643
V5       -0.094974
V9       -0.097733
V1       -0.101347
V18      -0.111485
V7       -0.187257
V3       -0.192961
V16      -0.196539
V10      -0.216883
V12      -0.260593
V14      -0.302544
V17      -0.326481
Name: Class, dtype: float64

In [13]:
X_train = strat_train_set.drop("Class", axis=1)

In [14]:
Y_train = strat_train_set["Class"].copy()

In [15]:
X_train.head()

Time        V1        V2        V3        V4        V5        V6  \
265518  161919.0  1.946747 -0.752526 -1.355130 -0.661630  1.502822  4.024933   
180305  124477.0  2.035149 -0.048880 -3.058693  0.247945  2.943487  3.298697   
42664    41191.0 -0.991920  0.603193  0.711976 -0.992425 -0.825838  1.956261   
198723  132624.0  2.285718 -1.500239 -0.747565 -1.668119 -1.394143 -0.350339   
82325    59359.0 -0.448747 -1.011440  0.115903 -3.454854  0.715771 -0.147490   

              V7        V8        V9  ...       V20       V21       V22  \
265518 -1.479661  1.139880  1.406819  ... -0.134435  0.076197  0.297537   
180305 -0.002192  0.674782  0.045826  ... -0.227279  0.038628  0.228197   
42664  -2.212603 -5.037523  0.000772  ...  1.280856 -2.798352  0.109526   
198723 -1.427984  0.010010 -1.118447  ... -0.490642 -0.139670  0.077013   
82325   0.504347 -0.113817 -0.044782  ... -0.275297 -0.243245 -0.173298   

             V23       V24       V25       V26       V27       V28  Amount  
265518  0.307915  0.690980 -0.350316 -0.388907  0.077641 -0.032248    7.32  
180305  0.035542  0.707090  0.512885 -0.471198  0.002520 -0.069002    2.99  
42664  -0.436530 -0.932803  0.826684  0.913773  0.038049  0.185340  175.10  
198723  0.208310 -0.538236 -0.278032 -0.162068  0.018045 -0.063005    6.10  
82325  -0.006692 -1.362383 -0.292234 -0.144622 -0.032580 -0.064194   86.10  

[5 rows x 30 columns]

In [16]:
Y_train

265518    0
180305    0
42664     0
198723    0
82325     0
         ..
233802    0
85418     0
29062     0
13766     0
17677     0
Name: Class, Length: 227845, dtype: int64

In [17]:
X_test = strat_test_set.drop("Class", axis=1)
X_test.head()

Time        V1        V2        V3        V4        V5        V6  \
263020  160760.0 -0.674466  1.408105 -1.110622 -1.328366  1.388996 -1.308439   
11378    19847.0 -2.829816 -2.765149  2.537793 -1.074580  2.842559 -2.153536   
147283   88326.0 -3.576495  2.318422  1.306985  3.263665  1.127818  2.865246   
219439  141734.0  2.060386 -0.015382 -1.082544  0.386019 -0.024331 -1.074935   
36939    38741.0  1.209965  1.384303 -1.343531  1.763636  0.662351 -2.113384   

              V7        V8        V9  ...       V20       V21       V22  \
263020  1.885879 -0.614233  0.311652  ...  0.394322  0.080084  0.810034   
11378  -1.795519 -0.250020  3.073504  ... -0.515765 -0.295555  0.109305   
147283  1.444125 -0.718922  1.874046  ...  2.034786 -1.060151  0.016867   
219439  0.207792 -0.338140  0.455091  ... -0.192024 -0.281684 -0.639426   
36939   0.854039 -0.475963 -0.629658  ...  0.009083 -0.164015 -0.328294   

             V23       V24       V25       V26       V27       V28  Amount  
263020 -0.224327  0.707899 -0.135837  0.045102  0.533837  0.291319   23.00  
11378  -0.813272  0.042996 -0.027660 -0.910247  0.110802 -0.511938   11.85  
147283 -0.132058 -1.483996 -0.296011  0.062823  0.552411  0.509764   76.07  
219439  0.331818 -0.067584 -0.283675  0.203529 -0.063621 -0.060077    0.99  
36939  -0.154631  0.619449  0.818998 -0.330525  0.046884  0.104527    1.50  

[5 rows x 30 columns]

In [18]:
Y_test = strat_test_set["Class"].copy()
Y_test

263020    0
11378     0
147283    0
219439    0
36939     0
         ..
54199     0
184616    0
274532    0
269819    0
64170     0
Name: Class, Length: 56962, dtype: int64

In [19]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

my_pipeline = Pipeline([('std_scaler', StandardScaler())])

pip_tr = my_pipeline.fit_transform(X_train)
pip_tr




array([[ 1.41158751,  0.99337908, -0.45603659, ...,  0.19191152,
        -0.09910576, -0.32249376],
       [ 0.62314085,  1.03850725, -0.02934912, ...,  0.00639701,
        -0.21152423, -0.33976388],
       [-1.13068022, -0.50676613,  0.36606499, ...,  0.09413695,
         0.56642647,  0.34669349],
       ...,
       [-1.25471074,  0.54569899,  0.04401572, ...,  0.07676455,
         0.07564817, -0.17053266],
       [-1.48398822,  0.65325241,  0.18256566, ..., -0.14759091,
        -0.0184768 , -0.34813969],
       [-1.39061787, -0.30573748,  0.47027277, ...,  0.93509494,
         0.63073809, -0.32380996]])

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
#model = SVC()
model = RandomForestClassifier(n_estimators=20)#it gave best predictions
#model = GaussianNB()
#model = LogisticRegression()
model.fit(pip_tr, Y_train)

RandomForestClassifier(n_estimators=20)

In [21]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(model, pip_tr, Y_train, cv=5, scoring = "accuracy")


In [22]:
def print_scores(score):
    print("score: ", score)
    print("mean: ", score.mean())
    print("SD :", score.std())
    
    
 

In [23]:
print_scores(score)

score:  [0.99945138 0.99951722 0.99951722 0.99949527 0.99953916]
mean:  0.9995040488051087
SD : 2.9767297869739225e-05


In [24]:
from sklearn.model_selection import cross_val_predict
Y_train_predict = cross_val_predict(model, pip_tr, Y_train, cv=5)

Y_train_predict



array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [25]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_train, Y_train_predict)



array([[227434,     17],
       [    95,    299]], dtype=int64)

In [26]:
from sklearn.metrics import f1_score, precision_score

print(precision_score(Y_train, Y_train_predict))
print(f1_score(Y_train, Y_train_predict))




0.9462025316455697
0.8422535211267607


In [27]:
X_test = strat_test_set.drop('Class', axis=1)
Y_test = strat_test_set['Class'].copy()
pip_test = my_pipeline.fit_transform(X_test)
final_prediction = model.predict(pip_test)
final_prediction

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [28]:
print(precision_score(Y_test, final_prediction))
print(f1_score(Y_test, final_prediction))


0.9294117647058824
0.8633879781420767


In [29]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,final_prediction))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.93      0.81      0.86        98

    accuracy                           1.00     56962
   macro avg       0.96      0.90      0.93     56962
weighted avg       1.00      1.00      1.00     56962

